services:
  ktauth:
    container_name: ktauth
    image: stellashiina/ktauth:latest
    ports:
      - "51214:51214"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - GIN_MODE=release
    restart: always
  postgres:
    container_name: ktauth-db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=ktauth
      - POSTGRES_PASSWORD=ktauth
      - POSTGRES_USER=ktauth
    restart: always
  redis:
    container_name: ktauth-redis
    image: redis:latest
    restart: always
volumes:
  postgres_data:
